### ISSUE TITLE
Add A Proposal ::::::: Nautical Symbols

### ISSUE THREAD

**Issue by cheznewa** [dscorbett/unifont-history#1]
Hello, Is Possible to add the proposal in 2012, the nautical symbols ::::::: https://www.unicode.org/L2/L2012/12061-nautical-chart.pdf

**Comment by dscorbett** [comment]
This repository simply tracks [GNU Unifont](https://unifoundry.com/unifont/index.html). If you want GNU Unifont to include the nautical symbols, you’ll have to wait till they are added to Unicode. Perhaps you could contact the proposal’s authors or send feedback to Unicode asking them to accept it. In any case, there’s nothing to do in this repository.
