### ISSUE TITLE
Unifont is blacklisted

### ISSUE THREAD

**Issue by yg8ijvjvjv** [dscorbett/unifont-history#2]
Unifont has been recognized to be made with design flaws. Many design flaws can be traced to Rebecca G. Bettencourt, a type non-designer that only makes unusable fonts with extremely many design flaws, and refused to self-promote on request. For instance, 25E2 is not properly the inverse of 25E4 (and 25E3 to 25E5, as well as many slopes in Legacy Computing). 

Paul Hardy misunderstands copyright. That Unifont has "GNU icon designs" and "GNU bitmapped letter forms" in it is nonsense. A few bytes per glyph is all it is, which can be freely written, distributed, converted, laser etched, soldered, etc. under the public domain. The copyrightable "computer program" of fonts refers exclusively to the hinting (which there virtually is none in a fake bitmap font) and to the outlines (which are gone when converted to bitmap), making the bitmaps uncopyrightable. Paul Hardy also refused to self-promote, and self-promotion is extremely important in free fontdevelopment.

Unifont is blacklisted. From the moral point of view, it is no different from a proprietary font.

**Comment by dscorbett** [comment]
This repository exists only to track Unifont’s history. Comments about Unifont’s design or copyright status can be reported upstream.

**Comment by yg8ijvjvjv** [comment]
I have also seen you made issues on Kreative (RebeccaRGB) fonts "open-relay". They have been closed with no explanation. Kreative fonts have extremely many design flaws such as exceeding vertical boundaries (unsigned Win Ascent and unsigned Win Descent, which should clip in all usable renderers and precisely determine line spacing and alignment), causing diacritics of capitals to clip, misaligned diagonal box drawing lines, etc. . She also accused me of "blackmailing" when what actually happened was a mandatory request to self-promote (all free software developers do similar things yet nobody calls it "blackmailing"). She dismisses the design flaw of exceeding vertical boundaries by insisting her specific render environment is the only correct environment. I recommend avoiding any Kreative fonts. They are blacklisted as well. Making issues on them won't go anywhere, so looking for competitors is the better option.

**Comment by yg8ijvjvjv** [comment]
If you have any concerns regarding the fundamentals of fontdevelopment, use fundamentals.fontdevelopment@protonmail.com
